---
spring:
  config:
    activate:
      on-profile: local, test, beta, prod
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      path: /h2-console
      enabled: true